-- Create database
CREATE SCHEMA EMPLOYEE;

-- Drop tables before creating new one
DROP TABLE IF EXISTS EMPLOYEE.EMPT01;

DROP TABLE IF EXISTS EMPLOYEE.EMPT02;

DROP TABLE IF EXISTS EMPLOYEE.EMPT03;

-- Create tables
-- Departments
CREATE TABLE EMPLOYEE.EMPT01 (
	T01F01 INT PRIMARY KEY, -- Department ID
	T01F02 VARCHAR NOT NULL UNIQUE, -- Name of department
	T01F03 VARCHAR -- Location of department
);

-- Employees
CREATE TABLE EMPLOYEE.EMPT02 (
	T02F01 INT PRIMARY KEY, -- Employee ID
	T02F02 VARCHAR NOT NULL, -- First name
	T02F03 VARCHAR NOT NULL, -- Last name
	T02F04 VARCHAR NOT NULL UNIQUE, -- Email
	T02F05 DATE NOT NULL, -- Hiring date
	T02F06 VARCHAR NOT NULL, -- Role
	T02F07 DECIMAL(10, 2) NOT NULL, -- Monthly salary
	T02F08 INT, -- Foreign key to Departments
	FOREIGN KEY (T02F08) REFERENCES EMPLOYEE.EMPT01 (T01F01)
);

-- Ex_employees
CREATE TABLE EMPLOYEE.EMPT03 (
	T03F01 INT PRIMARY KEY, -- Employee ID
	T03F02 VARCHAR NOT NULL, -- First name
	T03F03 VARCHAR NOT NULL, -- Last name
	T03F04 DATE NOT NULL -- When employee left
);

-- Alter table
-- Rename table
ALTER TABLE EMPLOYEE.DEPARTMENT
RENAME TO EMPT01;

-- Add new column
ALTER TABLE EMPLOYEE.EMPT01
ADD T01F04 TIMESTAMP;

-- Rename column
ALTER TABLE EMPLOYEE.EMPT01
RENAME COLUMN T01F04 TO TIMECREATED;

-- Drop column
ALTER TABLE EMPLOYEE.EMPT01
DROP COLUMN TIMECREATED;

-- Change data type
ALTER TABLE EMPLOYEE.EMPT01
ALTER COLUMN T01F03 TYPE VARCHAR(100);

-- Add primary key
ALTER TABLE EMPLOYEE.EMPT01
ADD CONSTRAINT PK_TO1 PRIMARY KEY (T01F01);

-- Drop forign key
ALTER TABLE EMPLOYEE.EMPT02
DROP CONSTRAINT T02_IBFK_1;

-- Add foreign key
ALTER TABLE EMPLOYEE.EMPT02
ADD CONSTRAINT FK_T02F08 FOREIGN KEY (T02F08) REFERENCES EMPLOYEE.EMPT01 (T01F01);

-- Drop unique constraint
ALTER TABLE EMPLOYEE.EMPT02
DROP CONSTRAINT T02F04;

-- Add unique constraint
ALTER TABLE EMPLOYEE.EMPT02
ADD CONSTRAINT T02F04_UNIQUE UNIQUE (T02F04);

-- Add check constraint
ALTER TABLE EMPLOYEE.EMPT02
ADD CONSTRAINT T02F07_CHECK CHECK (T02F07 > 0);

-- Add not null constraint
ALTER TABLE EMPLOYEE.EMPT02
ALTER COLUMN T02F02
SET NOT NULL;

-- Set default value
ALTER TABLE EMPLOYEE.EMPT02
ALTER COLUMN T02F05
SET DEFAULT (CURRENT_DATE);

-- Drop default values
ALTER TABLE EMPLOYEE.EMPT02
ALTER COLUMN T02F05
DROP DEFAULT;