
-- FUNCTION
DROP FUNCTION IF EXISTS EMPLOYEE.CALCULATE_AGE;

CREATE FUNCTION EMPLOYEE.CALCULATE_AGE (P_BIRTH_DATE DATE) RETURNS INT LANGUAGE PLPGSQL AS $$
DECLARE
	v_age INT;
BEGIN
    v_age = EXTRACT(YEAR FROM AGE(CURRENT_DATE, p_birth_date));
    RETURN v_age;
END;
$$;

SELECT
	EMPLOYEE.CALCULATE_AGE ('2010-10-10');

DROP FUNCTION IF EXISTS EMPLOYEE.GET_EMPLOYEE_BY_DEPARTMENT;

CREATE OR REPLACE FUNCTION EMPLOYEE.GET_EMPLOYEE_BY_DEPARTMENT (P_DEPT_NAME VARCHAR(50)) RETURNS TABLE (T02F01 INT, T02F02 VARCHAR, T02F03 VARCHAR) LANGUAGE PLPGSQL AS $$
BEGIN
    RETURN QUERY
    SELECT
        e.T02F01,
        e.T02F02,
        e.T02F03
    FROM employee.empt02 e
    JOIN employee.empt01 d ON e.T02F08 = d.T01F01
    WHERE d.T01F02 = p_dept_name;
END;
$$;

SELECT
	*
FROM
	EMPLOYEE.GET_EMPLOYEE_BY_DEPARTMENT ('Sales');

-- Procedure
DROP PROCEDURE IF EXISTS EMPLOYEE.COUNT_EMPLOYEE;

CREATE PROCEDURE EMPLOYEE.COUNT_EMPLOYEE (IN P_DEPT_NAME VARCHAR, OUT P_COUNT INT) LANGUAGE PLPGSQL AS $$
BEGIN
	SELECT
		COUNT(T02F08)
	INTO
		P_COUNT
	FROM 
		EMPLOYEE.EMPT02
        INNER JOIN EMPLOYEE.EMPT01 ON T02F08 = T01F01
	WHERE
		T01F02 = p_dept_name;
END$$

CALL EMPLOYEE.COUNT_EMPLOYEE ('Sales', NULL);

CREATE PROCEDURE double_number(INOUT p_num INT) LANGUAGE PLPGSQL AS $$
BEGIN
    p_num = p_num * 2;
END$$

CALL DOUBLE_NUMBER (5);

-- Trigger
DROP TRIGGER IF EXISTS LOG_DELETE_EMPLOYEE ON EMPLOYEE.EMPT02;
DROP FUNCTION IF EXISTS EMPLOYEE.LOG_DELETE_EMPLOYEE_FUNCTION CASCADE;


CREATE FUNCTION EMPLOYEE.LOG_DELETE_EMPLOYEE_FUNCTION()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
$$
BEGIN
	INSERT INTO EMPLOYEE.EMPT03 (T03F01, T03F02, T03F03, T03F04) VALUES
    (OLD.T02F01, OLD.T02F02, OLD.T02F03, CURRENT_DATE);

	RETURN OLD;
END
$$

CREATE TRIGGER LOG_DELETE_EMPLOYEE
BEFORE DELETE ON EMPLOYEE.EMPT02
FOR EACH ROW
EXECUTE PROCEDURE EMPLOYEE.LOG_DELETE_EMPLOYEE_FUNCTION();

SELECT
	*
FROM
	EMPLOYEE.EMPT02;

START TRANSACTION;
DELETE FROM EMPLOYEE.EMPT02;
ROLLBACK;

SELECT
	*
FROM
	EMPLOYEE.EMPT03;

-- Procedures WITH CURSOR
DROP PROCEDURE IF EXISTS FETCH_EMPLOYEE;

CREATE OR REPLACE PROCEDURE employee.fetch_employee(
    OUT p_employee TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_name TEXT;
    cur_employee CURSOR FOR
        SELECT T02F02 || T02F03
        FROM employee.empt02;
BEGIN
    p_employee := '';

    OPEN cur_employee;

    LOOP
        FETCH cur_employee INTO v_name;
        EXIT WHEN NOT FOUND;

        IF p_employee = '' THEN
            p_employee := v_name;
        ELSE
            p_employee := p_employee || ', ' || v_name;
        END IF;
    END LOOP;

    CLOSE cur_employee;
END;
$$;


CALL EMPLOYEE.FETCH_EMPLOYEE (NULL);