CREATE TABLE DEPARTMENTS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	MANAGER VARCHAR(255) NOT NULL
);

INSERT INTO
	DEPARTMENTS (NAME, MANAGER)
VALUES
	('Sales', 'a'),
	('Marketing', 'b'),
	('IT', 'c');

CREATE ROLE MANAGERS;

GRANT
SELECT
	ON ALL TABLES IN SCHEMA PUBLIC TO MANAGERS;

CREATE ROLE A
WITH
	LOGIN PASSWORD 'Miracle@123' IN ROLE MANAGERS;

CREATE ROLE B
WITH
	LOGIN PASSWORD 'Miracle@123' IN ROLE MANAGERS;

CREATE ROLE C
WITH
	LOGIN PASSWORD 'Miracle@123' IN ROLE MANAGERS;

ALTER TABLE DEPARTMENTS ENABLE ROW LEVEL SECURITY;

CREATE POLICY DEPARTMENT_MANAGERS ON DEPARTMENTS TO MANAGERS USING (MANAGER = CURRENT_USER);

SELECT
	*
FROM
	DEPARTMENTS;