SELECT
	*
FROM
	PG_ROLES;

-- CREATE ROLE
CREATE ROLE BOB;

-- CREATE LOGIN ROLE
CREATE ROLE ALICE LOGIN PASSWORD 'Miracle@123';

-- CREATE SUPERUSER ROLE
CREATE ROLE JOHN SUPERUSER LOGIN PASSWORD 'Miracle@123';

-- CREATE ROLE WITH DATABASE CREATION PERMISSION
CREATE ROLE DBA CREATEDB LOGIN PASSWORD 'Miracle@123';

-- CREATE ROLE WITH VALIDITY PERIOD
CREATE ROLE DEV_API
WITH
	LOGIN PASSWORD 'Miracle@123' VALID UNTIL '2026-02-08';

-- CREATE ROLE WITH CONNECTION LIMIT
CREATE ROLE API LOGIN PASSWORD 'Miracle@123' CONNECTION
LIMIT
	1000;

-- GRANT
-- IN PLACE OF SELECT WE CAN HAVE COMMA(,) SEPARATEDE VALUE OR ALL SAME FOR SALES
GRANT
SELECT
	ON SALES TO ALICE;

REVOKE
SELECT
	ON SALES
FROM
	ALICE;

-- GROUP ASSIGNMENT
GRANT BOB TO ALICE;

GRANT
SELECT
	ON SALES TO BOB;

SELECT
	CURRENT_USER;

ALTER ROLE DBA NOCREATEDB;

DROP ROLE DBA;

-- TO CHANGE PASSWORD
ALTER ROLE ALICE
WITH
	PASSWORD 'Miracle@123';