CREATE SCHEMA STUDENT_MANAGEMENT;

CREATE TABLE STUDENT_MANAGEMENT.STUDENTS
(
	STUDENT_ID INT GENERATED ALWAYS AS IDENTITY,
	FIRST_NAME TEXT,
	LAST_NAME TEXT,
	EMAIL TEXT,
	ENROLLMENT_DATE DATE
);

ALTER TABLE STUDENT_MANAGEMENT.STUDENTS
ADD COLUMN PHONE_NUMBER VARCHAR(10);

ALTER TABLE STUDENT_MANAGEMENT.STUDENTS
ADD CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL);

INSERT INTO STUDENT_MANAGEMENT.STUDENTS (FIRST_NAME, LAST_NAME, EMAIL, ENROLLMENT_DATE, PHONE_NUMBER) VALUES
('JOHN', 'DOE', 'JOHN.DOE@EXAMPLE.COM', '2023-10-27', '0123456789')
RETURNING STUDENT_ID, FIRST_NAME, LAST_NAME;

SELECT * FROM STUDENT_MANAGEMENT.STUDENTS;