CREATE VIEW CUSTOMER_INFO AS
SELECT
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	PHONE,
	CITY,
	POSTAL_CODE,
	COUNTRY
FROM
	CUSTOMER
	INNER JOIN ADDRESS USING (ADDRESS_ID)
	INNER JOIN CITY USING (CITY_ID)
	INNER JOIN COUNTRY USING (COUNTRY_ID);

SELECT
	*
FROM
	CUSTOMER_INFO;

SELECT
	*
FROM
	CUSTOMER_LIST;

CREATE MATERIALIZED VIEW RENTAL_BY_CATEGORY AS
SELECT
	C.NAME AS CATEGORY,
	SUM(P.AMOUNT) AS TOTAL_SALES
FROM
	(
		(
			(
				(
					(
						PAYMENT P
						JOIN RENTAL R ON ((P.RENTAL_ID = R.RENTAL_ID))
					)
					JOIN INVENTORY I ON ((R.INVENTORY_ID = I.INVENTORY_ID))
				)
				JOIN FILM F ON ((I.FILM_ID = F.FILM_ID))
			)
			JOIN FILM_CATEGORY FC ON ((F.FILM_ID = FC.FILM_ID))
		)
		JOIN CATEGORY C ON ((FC.CATEGORY_ID = C.CATEGORY_ID))
	)
GROUP BY
	C.NAME
ORDER BY
	SUM(P.AMOUNT) DESC
WITH
	NO DATA;

CREATE UNIQUE INDEX RENTAL_CATEGORY ON RENTAL_BY_CATEGORY (CATEGORY);

REFRESH MATERIALIZED VIEW CONCURRENTLY RENTAL_BY_CATEGORY;

SELECT
	*
FROM
	RENTAL_BY_CATEGORY;