CREATE TABLE PRODUCT_GROUPS (
	GROUP_ID SERIAL PRIMARY KEY,
	GROUP_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTS (
	PRODUCT_ID SERIAL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	PRICE DECIMAL(11, 2),
	GROUP_ID INT NOT NULL,
	FOREIGN KEY (GROUP_ID) REFERENCES PRODUCT_GROUPS (GROUP_ID)
);

INSERT INTO
	PRODUCT_GROUPS (GROUP_NAME)
VALUES
	('Smartphone'),
	('Laptop'),
	('Tablet');

INSERT INTO
	PRODUCTS (PRODUCT_NAME, GROUP_ID, PRICE)
VALUES
	('Microsoft Lumia', 1, 200),
	('HTC One', 1, 400),
	('Nexus', 1, 500),
	('iPhone', 1, 900),
	('HP Elite', 2, 1200),
	('Lenovo Thinkpad', 2, 700),
	('Sony VAIO', 2, 700),
	('Dell Vostro', 2, 800),
	('iPad', 3, 700),
	('Kindle Fire', 3, 150),
	('Samsung Galaxy Tab', 3, 200);

SELECT
	PRODUCT_NAME,
	PRICE,
	GROUP_NAME,
	AVG(PRICE) OVER W,
	SUM(PRICE) OVER W,
	MIN(PRICE) OVER W,
	MAX(PRICE) OVER W,
	COUNT(PRICE) OVER W
FROM
	PRODUCTS
	INNER JOIN PRODUCT_GROUPS USING (GROUP_ID)
WINDOW
	W AS (
		PARTITION BY
			GROUP_NAME
	);

-- CUME_DIST
CREATE TABLE SALES_STATS (
	NAME VARCHAR(100) NOT NULL,
	YEAR SMALLINT NOT NULL CHECK (YEAR > 0),
	AMOUNT DECIMAL(10, 2) CHECK (AMOUNT >= 0),
	PRIMARY KEY (NAME, YEAR)
);

INSERT INTO
	SALES_STATS (NAME, YEAR, AMOUNT)
VALUES
	('John Doe', 2018, 120000),
	('Jane Doe', 2018, 110000),
	('Jack Daniel', 2018, 150000),
	('Yin Yang', 2018, 30000),
	('Stephane Heady', 2018, 200000),
	('John Doe', 2019, 150000),
	('Jane Doe', 2019, 130000),
	('Jack Daniel', 2019, 180000),
	('Yin Yang', 2019, 25000),
	('Stephane Heady', 2019, 270000);

SELECT
	NAME,
	YEAR,
	AMOUNT,
	CUME_DIST() OVER (
		ORDER BY
			AMOUNT
	)
FROM
	SALES_STATS
WHERE
	YEAR = 2018;

SELECT
	NAME,
	YEAR,
	AMOUNT,
	CUME_DIST() OVER (
		PARTITION BY
			YEAR
		ORDER BY
			AMOUNT
	)
FROM
	SALES_STATS;

-- DENSE_RANK, RANK, ROW_NUMBER
CREATE TABLE DENSE_RANKS (C VARCHAR(10));

INSERT INTO
	DENSE_RANKS (C)
VALUES
	('A'),
	('A'),
	('B'),
	('C'),
	('C'),
	('D'),
	('E');

SELECT
	C,
	ROW_NUMBER() OVER W,
	RANK() OVER W,
	DENSE_RANK() OVER W
FROM
	DENSE_RANKS
WINDOW
	W AS (
		ORDER BY
			C
	);

-- FIRST_VALUE, LAST_VALUE
SELECT
	PRODUCT_ID,
	PRODUCT_NAME,
	GROUP_ID,
	PRICE,
	FIRST_VALUE(PRODUCT_NAME) OVER W LOWEST_PRICE,
	LAST_VALUE(PRODUCT_NAME) OVER W HIGHEST_PRICE,
	NTH_VALUE(PRODUCT_NAME, 2) OVER W
FROM
	PRODUCTS
WINDOW
	W AS (
		PARTITION BY
			GROUP_ID
		ORDER BY
			PRICE RANGE BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	);

-- LAG, LEAD
DROP TABLE SALES;

CREATE TABLE SALES (
	YEAR SMALLINT CHECK (YEAR > 0),
	GROUP_ID INT NOT NULL,
	AMOUNT DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY (YEAR, GROUP_ID)
);

INSERT INTO
	SALES (YEAR, GROUP_ID, AMOUNT)
VALUES
	(2018, 1, 1474),
	(2018, 2, 1787),
	(2018, 3, 1760),
	(2019, 1, 1915),
	(2019, 2, 1911),
	(2019, 3, 1118),
	(2020, 1, 1646),
	(2020, 2, 1975),
	(2020, 3, 1516)
RETURNING
	*;

SELECT
	*
FROM
	SALES;

SELECT
	YEAR,
	GROUP_ID,
	AMOUNT,
	LAG(AMOUNT, 1, 0) OVER W AS PREVIOUS_YEAR_SALE,
	LEAD(AMOUNT, 1, 0) OVER W AS NEXT_YEAR_SALE
FROM
	SALES
WINDOW
	W AS (
		PARTITION BY
			GROUP_ID
		ORDER BY
			YEAR
	)
ORDER BY
	YEAR,
	GROUP_ID;

-- NTILE
SELECT
	NAME,
	AMOUNT,
	YEAR,
	NTILE(3) OVER (
		PARTITION BY
			YEAR
		ORDER BY
			AMOUNT
	)
FROM
	SALES_STATS;

-- Percent_rank
SELECT
	NAME,
	AMOUNT,
	YEAR,
	PERCENT_RANK() OVER (
		PARTITION BY
			YEAR
		ORDER BY
			AMOUNT
	)
FROM
	SALES_STATS;

-- find nth largest price
SELECT
	*
FROM
	PRODUCTS
WHERE
	PRICE = (
		SELECT
			PRICE
		FROM
			(
				SELECT
					PRICE,
					ROW_NUMBER() OVER (
						ORDER BY
							PRICE DESC
					) AS NTH
				FROM
					(
						SELECT DISTINCT
							(PRICE)
						FROM
							PRODUCTS
					) PRICES
			) SORTED_PRICES
		WHERE
			NTH = 3
	);

SELECT
	*
FROM
	(
		SELECT
			*,
			DENSE_RANK() OVER (
				ORDER BY
					PRICE DESC
			) AS RNK
		FROM
			PRODUCTS
	) T
WHERE
	RNK = 3;